--CREATE TABLE oficiales (
  --id_oficial integer PRIMARY KEY AUTOINCREMENT,
  --nombre varchar(150) NOT NULL,
  --apellido_paterno varchar(150) NOT NULL,
  --apellido_materno varchar(150),
  --adscripcion varchar(150) NOT NULL,
  --cargo_grado varchar(150) NOT NULL,
  --matricula varchar(30) not null unique,  
  --passw varchar(32) NOT NULL
--);

--INSERT INTO oficiales (nombre, apellido_paterno, apellido_materno, cargo_grado, abscripcion, num_patrulla, passw) VALUES 
--("Federico", "Hernandez", "Leyva", "Administrativa", "Subalterno","2564_Ab", "IHbyg3nj");